micronaut:
  application:
    name: flixwrapped
  server:
    port: 8080
  cors:
    cors:
      enabled: true
      configurations:
        default:
          allowed-origins:
            - "https://flix-wrapped-ui.vercel.app"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - "*"
          allow-credentials: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**

frontend:
  url: ${FRONTEND_URL}

auth:
  clientId: ${GOOGLE_CLIENT_ID}
  secretKey: ${GOOGLE_SECRET_KEY}

omdb:
  apikey: ${OMDB_API_KEY}
  url: http://www.omdbapi.com/

mongodb:
  uri: ${MONGODB_URI}
  database: flix-wrapped
  package-names: com.ramonlimas.domain.model
  collections:
    history-processed: history_processed
